baseURL = "https://angr.io/"
languageCode = "en-us"
title = "angr"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["RSS"]

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "code"
  url = "https://github.com/angr"
  weight = 2
[[menu.main]]
  name = "docs"
  url = "https://docs.angr.io/"
  weight = 3
[[menu.main]]
  name = "blog"
  url = "/blog"
  weight = 4
[[menu.main]]
  name = "get involved!"
  url = "/#contact"
  weight = 5

[taxonomies]
  tag = "tags"
  author = "authors"

[params]

[permalinks]
  top = "/:filename/"

[markup.goldmark.renderer]
unsafe = true
