baseURL = "https://angr.io/"
languageCode = "en-us"
title = "angr"
pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "code"
  url = "https://github.com/angr"
  weight = 2
[[menu.main]]
  name = "docs"
  url = "https://docs.angr.io/"
  weight = 3
[[menu.main]]
  name = "api"
  url = "https://api.angr.io/"
  weight = 4
[[menu.main]]
  name = "blog"
  url = "/blog"
  weight = 5
[[menu.main]]
  name = "get involved!"
  url = "/#contact"
  weight = 6

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  announcement = "The angr team is offering a two-day training on August 15-16th! Come to DEFCON 30 and become an angr expert. [Click here to learn more.](https://defcontrainings.myshopify.com/products/fish-wang-customizable-binary-analysis-using-angr-to-its-full-potential)"

[permalinks]
  top = "/:filename/"

[markup.goldmark.renderer]
unsafe = true
