baseURL = "https://angr.io/"
languageCode = "en-us"
title = "angr"
pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "blog"
  url = "/blog"
  weight = 2
[[menu.main]]
  name = "docs"
  url = "http://docs.angr.io/"
  weight = 3
[[menu.main]]
  name = "code"
  url = "https://github.com/angr"
  weight = 4
[[menu.main]]
  name = "get involved!"
  url = "/#contact"
  weight = 5

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  announcement = "angr 8 is out! This release migrates angr to Python 3 and **drops Python 2 support**, in addition to bringing a bunch of performance improvements and bugfixes. For more details, see [here](/blog/moving_to_angr_8)."

[permalinks]
  top = "/:filename/"

[markup.goldmark.renderer]
unsafe = true
