on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install hugo

    - name: Build
      run: hugo

    - name: Generate CNAME
      run: |
        pushd public
        echo "angr.io" > CNAME
        echo "www.angr.io" >> CNAME
        echo "angr.re" >> CNAME
        echo "www.angr.re" >> CNAME
        echo "angr.horse" >> CNAME
        echo "www.angr.horse " >> CNAME

    # Temporarily integrate API docs for domain migration
    - name: Integrate API docs
      run: |
        pushd /tmp
        git clone https://github.com/angr/angr.github.io
        popd
        mv /tmp/angr.github.io/api-doc public/api-doc

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
